name: Sincronizacion Automatizada LGA

on:
  push:
    branches:
      - master

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Espejar en repositorio del cliente
        env:
          CLIENT_TOKEN: $\{{ secrets.CLIENT_GITHUB_TOKEN \}}
        run: |
          git config --global user.name "LGA Sync Bot"
          git config --global user.email "bot@aricaesbacan.cl"
          git push -f https://mabychile:$\{{ env.CLIENT_TOKEN \}@github.com/lgaaricaesbacan/La_Gran_Arica.git master
